apiVersion: skaffold/v2beta29
kind: Config
profiles:
- name: development
  activation:
  - command: dev
  build:
    local:
      useBuildkit: true
    artifacts:
    - image: dependency-check-enclave
      context: .
      docker: {}
  deploy:
    kubeContext: minikube
    helm:
      releases:
      - name: dependency-check-enclave
        chartPath: .helm
        artifactOverrides:
          image: dependency-check-enclave
        imageStrategy:
          helm: {}
        setValueTemplates:
          image.pullPolicy: Never